### ISSUE TITLE
Support for recurring payments

### ISSUE THREAD

**Issue by WebsiteFactoryTM** [chesscoders/netopia-card#10]
Salut, in primul rand vreau sa mentionez ca mi-o fost greu sa gasesc modulul asta si ma bucur ca l-am gasit, foarte buna treaba :)
In al doilea rand, nu am vazut sa fie optiune de plata recurenta, oare este in curs de development? 
Momentan ma gandesc sa extind clasa voastra si sa adaug parametrii necesari pentru asta, dar sunt curios daca aveti voi deja pe pipeline asta.

Mersi
Alex

**Comment by victorocna** [comment]
Salutare! Multumim frumos pentru aprecieri. Din pacate nu avem in dezvoltare plata recurenta. Daca doresti sa contribui la acest pachet esti binevenit si iti multumesc de acum.
