### ISSUE TITLE
Expose language config constructor

### ISSUE THREAD

**Issue by 0x963D** [chesscoders/netopia-card#16]
Hello guys, 

Great work with the package, its working like a charm! 
One question/request: is it possible to access or expose the language config setting which is defaulted to "ro" at the moment:
```
this.config = { language: 'ro' };
```
I would like to customize the checkout experience for each client based on his preferred language. 

All the best,
Dan

**Comment by mihai-dulgheru** [comment]
Hello Dan,

Thank you for your kind words and for using our package!

We’re happy to inform you that we’ve implemented your requested functionality. Starting with version **2.1.1**, you can now customize the language setting for the checkout experience.

By default, the language is still set to "ro", but you can now easily override this by passing the `language` parameter when initializing the `Netopia` instance. Here's how you can do it:

```javascript
const netopia = new Netopia({
  apiKey: 'your-api-key',
  notifyUrl: 'https://your-notify-url',
  posSignature: 'your-pos-signature',
  redirectUrl: 'https://your-redirect-url',
  language: 'en', // Set the language to 'en' or any other supported language
});
```

We hope this enhancement helps you tailor the checkout experience to your client's preferences.

All the best,
Mihai

**Comment by 0x963D** [comment]
Hello Mihai,

Thank you so much, I appreciate your work to get this published!
I've just deployed it to production and its working as expected.

All the best,
Dan
