### ISSUE TITLE
RC4_BUILDER_ERROR - eroare

### ISSUE THREAD

**Issue by silviuvld** [chesscoders/netopia-card#9]
Salutare,

Incerc sa integrez plata cu cardul intr-un API facut in Node si am dat de biblioteca voastra.

Buna treaba, apreciez.

Oare stiti de ce primesc eroarea asta? Am incercat sa reproduc exemplu vostru din Readme, nimic diferit.
Atasez o poza pt context.

![Screenshot 2023-12-07 at 14 29 53](https://github.com/chesscoders/netopia-card/assets/102789727/deeb7a4e-573f-420b-9522-04ddf0882dd4)

Mersi

**Comment by yokrysty** [comment]
Buna,
eu folosesc aceasta librarie fara probleme
eroarea ta pare ca vine de aici, in index.js
![image](https://github.com/chesscoders/netopia-card/assets/9500609/ca5cc2e1-3b6b-4cdc-9a3e-164b45bff440)
ceea ce ma face sa cred ca este ceva in neregula cu public key
nu-mi pot da seama de problema cat timp nu iti cunosc cheia :)
poti pune un breakpoint sau un `console.error(e)` in acel catch pe copia ta locala din node_modules
